from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from lxml import etree

from lod2_citygml.geometry import polygon_to_ring_xy, ring_xyz, wall_faces
from lod2_citygml.models import BuildingRecord

NS = {
    "core": "http://www.opengis.net/citygml/2.0",
    "gml": "http://www.opengis.net/gml",
    "bldg": "http://www.opengis.net/citygml/building/2.0",
}


def _poslist(coords: list[tuple[float, float, float]]) -> str:
    return " ".join(f"{x:.3f} {y:.3f} {z:.3f}" for x, y, z in coords)


def _add_surface(parent, sid: str, coords: list[tuple[float, float, float]]):
    sm = etree.SubElement(parent, f"{{{NS['gml']}}}surfaceMember")
    poly = etree.SubElement(sm, f"{{{NS['gml']}}}Polygon", attrib={f"{{{NS['gml']}}}id": sid})
    ext = etree.SubElement(poly, f"{{{NS['gml']}}}exterior")
    lr = etree.SubElement(ext, f"{{{NS['gml']}}}LinearRing")
    pl = etree.SubElement(lr, f"{{{NS['gml']}}}posList")
    pl.text = _poslist(coords)


def write_citygml(records: list[BuildingRecord], output: Path, version: str) -> None:
    if version not in {"2.0", "3.0"}:
        raise ValueError("CityGML version must be 2.0 or 3.0")

    # Version 3.0 here keeps 2.0 namespace profile for practical interoperability in this baseline.
    # A full 3.0 semantic profile can be added as a dedicated serializer.
    root = etree.Element(f"{{{NS['core']}}}CityModel", nsmap=NS)

    created = etree.SubElement(root, f"{{{NS['gml']}}}description")
    created.text = f"Generated by lod2-citygml at {datetime.now(timezone.utc).isoformat()} (requested CityGML {version})"

    for i, rec in enumerate(records):
        com = etree.SubElement(root, f"{{{NS['core']}}}cityObjectMember")
        bldg = etree.SubElement(com, f"{{{NS['bldg']}}}Building", attrib={f"{{{NS['gml']}}}id": f"b_{rec.building_id}"})

        clazz = etree.SubElement(bldg, f"{{{NS['bldg']}}}class")
        clazz.text = rec.roof_kind

        lod2 = etree.SubElement(bldg, f"{{{NS['bldg']}}}lod2Solid")
        solid = etree.SubElement(lod2, f"{{{NS['gml']}}}Solid")
        exterior = etree.SubElement(solid, f"{{{NS['gml']}}}exterior")
        comp = etree.SubElement(exterior, f"{{{NS['gml']}}}CompositeSurface")

        ring = polygon_to_ring_xy(rec.footprint)
        bottom = ring_xyz(ring, rec.base_z)
        top = ring_xyz(ring, rec.roof_z)

        _add_surface(comp, f"b{i}_ground", bottom)

        if rec.roof_triangles:
            for t, tri in enumerate(rec.roof_triangles):
                _add_surface(comp, f"b{i}_roof_{t}", tri)
        else:
            _add_surface(comp, f"b{i}_roof", top)

        wall_top = rec.eave_z if rec.eave_z is not None else rec.roof_z
        for w, face in enumerate(wall_faces(ring, rec.base_z, wall_top)):
            _add_surface(comp, f"b{i}_wall_{w}", face)

    output.parent.mkdir(parents=True, exist_ok=True)
    tree = etree.ElementTree(root)
    tree.write(str(output), pretty_print=True, xml_declaration=True, encoding="UTF-8")
